{{- include "buzz.validate" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "buzz.fullname" . }}
  labels:
    {{- include "buzz.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "buzz.relaySelectorLabels" . | nindent 4 }}
  ports:
    - { name: app,     port: {{ .Values.service.port }},        targetPort: app,     protocol: TCP }
    - { name: health,  port: {{ .Values.service.healthPort }},  targetPort: health,  protocol: TCP }
    - { name: metrics, port: {{ .Values.service.metricsPort }}, targetPort: metrics, protocol: TCP }
