import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: "./tests/e2e",
  timeout: 30_000,
  retries: process.env.CI ? 2 : 0,
  workers: 1,
  reporter: [
    ["list"],
    ["html", { open: "never", outputFolder: "playwright-report" }],
  ],
  use: {
    baseURL: "http://127.0.0.1:4173",
    screenshot: "only-on-failure",
    trace: "on-first-retry",
    video: "retain-on-failure",
  },
  projects: [
    {
      name: "smoke",
      testMatch: [
        "**/smoke.spec.ts",
        "**/navigation.spec.ts",
        "**/channels.spec.ts",
        "**/channel-shared-header-backdrop.spec.ts",
        "**/badge.spec.ts",
        "**/channel-browser.spec.ts",
        "**/messaging.spec.ts",
        "**/custom-emoji.spec.ts",
        "**/profile-custom-emoji-status.spec.ts",
        "**/custom-emoji-ui.spec.ts",
        "**/channel-mute.spec.ts",
        "**/channel-star.spec.ts",
        "**/channel-controls.spec.ts",
        "**/active-turn-resilience.spec.ts",
        "**/profile-active-turn.spec.ts",
        "**/config-bridge-screenshots.spec.ts",
        "**/observer-feed-screenshots.spec.ts",
        "**/activity-scope-label-screenshots.spec.ts",
        "**/local-archive-screenshots.spec.ts",
        "**/agent-readiness-screenshots.spec.ts",
        "**/pubkey-display-screenshots.spec.ts",
        "**/file-attachment.spec.ts",
        "**/image-attachment-gallery.spec.ts",
        "**/composer-image-draw.spec.ts",
        "**/video-attachment.spec.ts",
        "**/spoiler.spec.ts",
        "**/composer-tooltip-dismiss.spec.ts",
        "**/mentions.spec.ts",
        "**/relay-reconnect.spec.ts",
        "**/relay-reconnect-affordance.spec.ts",
        "**/workflows.spec.ts",
        "**/identity-archive.spec.ts",
        "**/identity-archive-hide.spec.ts",
        "**/relay-connectivity.spec.ts",
        "**/unread-pill.spec.ts",
        "**/sidebar-more-unread-overlap.spec.ts",
        "**/home-collapsed-top-chrome.spec.ts",
        "**/top-chrome-zoom-clearance.spec.ts",
        "**/thread-unread.spec.ts",
        "**/workspace-rail.spec.ts",
        "**/thread-reply-anchor-roleplay.spec.ts",
        "**/threadpane-ultrawide.spec.ts",
        "**/animated-avatar.spec.ts",
        "**/reminders.spec.ts",
        "**/virtualization.spec.ts",
        "**/scroll-history.spec.ts",
        "**/channel-dense-second-reach.spec.ts",
        "**/channel-window-mock-paging.spec.ts",
        "**/live-broadcast-reply-timeline.spec.ts",
        "**/overscroll-boundary.spec.ts",
        "**/cold-switch-longtask.perf.ts",
        "**/timeline-no-shift.spec.ts",
        "**/human-edit-agent-content.spec.ts",
        "**/reaction-order.spec.ts",
        "**/reaction-names.spec.ts",
        "**/inbox-reactions.spec.ts",
        "**/send-channel-binding.spec.ts",
        "**/project-commit-detail.spec.ts",
        "**/persona-model-combobox-screenshots.spec.ts",
        "**/drafts-screenshots.spec.ts",
        "**/channel-sort.spec.ts",
      ],
      use: {
        ...devices["Desktop Chrome"],
      },
    },
    {
      name: "integration",
      testMatch: [
        "**/agents.spec.ts",
        "**/onboarding.spec.ts",
        "**/stream.spec.ts",
        "**/integration.spec.ts",
        "**/profile.spec.ts",
        "**/sidebar.spec.ts",
        "**/sidebar-relay-card.spec.ts",
        "**/tokens.spec.ts",
        "**/persona-env-vars.spec.ts",
        "**/persona-sync.spec.ts",
        "**/mesh-compute.spec.ts",
        "**/parity-ancestor-island.spec.ts",
      ],
      use: {
        ...devices["Desktop Chrome"],
      },
      expect: {
        timeout: process.env.CI ? 15_000 : 10_000,
      },
    },
  ],
  webServer: {
    command: "python3 -m http.server 4173 -d dist",
    cwd: ".",
    reuseExistingServer: !process.env.CI,
    url: "http://127.0.0.1:4173",
  },
});
